# Generated by Django 3.0.7 on 2020-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=40)),
                ('your_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
